### ISSUE TITLE
I can't connect. I don't know how to solve problem

### ISSUE THREAD

**Issue by Feskai** [vedfi/mondroid#11]
![IMG_20230612_224952.jpg](https://github.com/vedfi/mondroid/assets/47091919/ba9e70b8-9424-4c40-baa8-6796b0f99add)

mongodb+srv://<username>:<password>@cluster0discors.v499ape.mongodb.net/

I was not given the value of the "port" parameter

**Comment by vedfi** [comment]
Hello. Since you are connecting to an atlas database, the mongodb driver automatically detects the port number. It seems like this error is not caused by mondroid or mongodart driver. I see that you are using LTE network connection. You can try WiFi (Local ISP) connection.

**Comment by Feskai** [comment]
![IMG_20230612_232324.jpg](https://github.com/vedfi/mondroid/assets/47091919/d0cd0c7f-4932-4927-98c9-12dff73d079a)

It does not help

**Comment by vedfi** [comment]
Make sure that ip address 0.0.0.0 is allowed in Atlas Server. 

Try adding ssl=true&authSource=admin to your connecting string.

If above methods not working you may try this;
In Atlas Server IP Whitelist Page. Instead of clicking my current ip address, just search what's my ip on google and paste that instead.
